version: '3.8'

services:
  server:
    build:
      context: ./server
    restart: always
    environment:
      # Use o IP da sua VPS aqui se o Postgres estiver rodando nela
      DB_HOST: ${DB_HOST:-72.60.241.130}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-00770425143}
      DB_NAME: ${DB_NAME:-n8comunidade}
      DB_PORT: ${DB_PORT:-2391}
      JWT_SECRET: ${DB_PASSWORD:-supersecretneighborhoodkey123}
      PORT: 3333
    ports:
      - "3333:3333"

  client:
    build:
      context: ./client
    restart: always
    environment:
      REACT_APP_API_URL: http://server:3333
    ports:
      - "80:80"
